name: test-build
on: [push]
jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - uses: actions-rs/toolchain@v1
        with:
          components: rustfmt
          toolchain: stable
      - uses: davidB/rust-cargo-make@v1
      - run: cargo make build-webgl-sha1 -p release
