name: build & deploy stable
on:
  push:
    branches:
      - master
jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - uses: actions-rs/toolchain@v1
        with:
          components: rustfmt
          toolchain: stable
          target: wasm32-unknown-unknown
      - uses: davidB/rust-cargo-make@v1
      - run: ./deploy_stable.sh
